### ISSUE TITLE
GitHub repo icon missing

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimibook#22]
Not sure why, but we lost the GitHub repo icon. At a first look code looks fine: repo url is set in nbook, should be dumped in book.json, should be loaded in useNimibook and put in the context.

**Comment by pietroppeter** [comment]
I checked and in book.json both `title` and `git_repository_url` are missing

**Comment by pietroppeter** [comment]
well, `title` is never populated so that is fine. The weird thing is that using `dump` the json is correct. Doing build I cannot see anywhere where the book.json is generated. Sending a fix for this now, but if someone know what is happening in this case let me know.

**Comment by HugoGranstrom** [comment]
I think the problem is that `dump` is called already in `newBookFromToc` [here](https://github.com/pietroppeter/nimibook/blob/2e2d2ec2c39e2a0fcc6b3fa580ed0caff4939476/src/nimibook/tocs.nim#L80) and we add the repo link afterwards. So the correct placement is where you have put it now.

**Comment by pietroppeter** [comment]
Ah good spotting, that is where it was, I will remove it from there
