### ISSUE TITLE
Book.json as a build output

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimibook#23]
Book.json I think should be moved as an output to docs and I think it should be kept as a build output (not cleaned at the end of build, committed in gh-pages). It can be thought as a static api for the whole book. Thoughts?

**Comment by HugoGranstrom** [comment]
I see no reason against it really. If someone can have use of it I say we keep `book.json`, and putting it in `nbHomeDir` would potentially solve #21.

**Comment by pietroppeter** [comment]
fixed in #50
