### ISSUE TITLE
next/previous

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimibook#28]
should be rather straightforward to implement:
* looking at `document.mustache` [starting from this line but also in a later section](https://github.com/pietroppeter/nimibook/blob/main/src/nimibook/resources/templates/document.mustache#L189) we need to provide (if relevant) a next or previous object with a `link` field inside the context (or maybe we can simplify and provide `next` and `previous` fields directly as link, do not see why the need for a more complex object).
* this next and previous links must be generated in `nimibook.docs` [while processing the toc](https://github.com/pietroppeter/nimibook/blob/main/src/nimibook/resources/templates/document.mustache#L189)

**Comment by HugoGranstrom** [comment]
- I agree that it sounds easier and more obvious to just have `next` and `previous` fields in the context 👍 
- OK, does the `mitems` iterate in the correct order already? Or will we have to iterate over index instead to be able to set `previous = entries[i-1]` and `next = entries[i+1]`?

**Comment by pietroppeter** [comment]
It should iterate correctly but I guess iterating over the index is simpler in this case

**Comment by pietroppeter** [comment]
Are you planning to pick this up? ;)

**Comment by HugoGranstrom** [comment]
> It should iterate correctly but I guess iterating over the index is simpler in this case

Ok great! 👍 

How hard can it be? I have it all lined up before me on a silver plate. Of course I will stumble upon some obscure bug if I try it 🤣 I'm in! 😎
