### ISSUE TITLE
next/previous links have always href="./"

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimibook#30]
this line does something that is not expected: https://github.com/pietroppeter/nimibook/blob/main/src/nimibook/resources/templates/document.mustache#L189

**Comment by HugoGranstrom** [comment]
😫 I never tried running it on a server, only locally :/
Can it have something to do with `entry.url` not doing the same locally as online?

**Comment by pietroppeter** [comment]
I have no clue why it is not working as expected. I cannot see why [`entry.url`](https://github.com/pietroppeter/nimibook/blob/main/src/nimibook/entries.nim#L4) should work any different locally vs server (and anyway [it is used in rendering the toc](https://github.com/pietroppeter/nimibook/blob/gh-pages/src/nimibook/render.nim#L29), and in that case it works fine).
To me the implementation looks fine but there is defintely something not working correctly.

**Comment by HugoGranstrom** [comment]
Hmm it seems to be something wrong with the Github CI then because when I build it on Netlify [here](https://confident-heisenberg-b22ee0.netlify.app/index.html) the buttons suddenly work. And I'm just doing `nim r getting_started.nim build` 🤔

**Comment by pietroppeter** [comment]
Yes. Nice work on Netlify!

**Comment by pietroppeter** [comment]
I tested with a commit to see if this issue disappears (I see next/previous working fine on SciNim/getting-started) but it still there. I guess there is some difference in set up of nimibook or CI.

**Comment by HugoGranstrom** [comment]
So strange... The only real difference I can see between the build scripts is that you use `nimble genbook` and we do `nim c getting_started.nim`, `getting_started init`, `getting_started build`

**Comment by HugoGranstrom** [comment]
Another notable difference is that you have a bunch of `config.nims` files changing paths while we don't.

**Comment by pietroppeter** [comment]
ok, after struggling a little with adding plausible analytics directly in `book` api I know understand where this issue is coming from and I was also able to fix it. The issue in the CI that does rebase gh-pages on main and gh-pages has a lot of cruft that stays there (every file removed in main is still present in hg-pages). It does not help that build mechanism will not replace the document.mustache if one was commited. The simple fix was to remove artificially document.mustache in gh-pages and push another commit to rerun CI.

Better fixes planned:
- #33
- #32
