### ISSUE TITLE
Cannot Open Markdown Files

### ISSUE THREAD

**Issue by kerrycobb** [pietroppeter/nimibook#38]
After looking at the nimibook documentation I would expect this to work:

I have a project directory that looks like this:
```
├── book
│   └── index.md
├── nbook
└── nbook.nim
```

The `nbook.nim` file looks like this:
```nim
import nimibook

var book = newBookFromToc("nimibook", "book"):
  entry("Introduction", "index.md")

nimibookCli(book)
```

When I try to build this, I get this error: `Error: unhandled exception: cannot open: book/page.md [IOError]`

This seems like it might be a bug or like it would be helpful to explain in the documentation.

**Comment by pietroppeter** [comment]
￼Thanks for reporting, I was able to reproduce this, it is indeed a big related to path handling in nimib. I will fix it.
