### ISSUE TITLE
rename nimiBook to nimibook

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimibook#4]
this is a small thing but it kind of bothers me. the name was nimiBook as a calque of mdBook, but then I do not like that I have `nimiBook.nimble` files, hence the renaming. I guess this might be a bit bothering since we will have to change the remoteUrl of git repo (not sure what happens to the forks), so I figure I ask before proceeding. Thoughts @Clonkk, @HugoGranstrom?

**Comment by Clonkk** [comment]
Looks good to me

**Comment by HugoGranstrom** [comment]
Go ahead! 👌

**Comment by pietroppeter** [comment]
done!
