### ISSUE TITLE
Use different "book" directory

### ISSUE THREAD

**Issue by casey-SK** [pietroppeter/nimibook#48]
Can you change the value "book" in the newBookFromToc() call? I run into errors when changing it to anything else. If it is designed to be changed, then some sort of error is occurring here.

**Comment by pietroppeter** [comment]
You probably need also to change it in nimib.toml (which was introduced later) but I agree this is not ideal

**Comment by pietroppeter** [comment]
now `newBookFromToc` is deprecated and you should use `initBookFromToc`. Changing the directories in `nimib.toml` allows to change src and out directories for nimibook. fixed in #50
