### ISSUE TITLE
broken CI after renaming nimble file

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimibook#5]
https://github.com/pietroppeter/nimibook/runs/2617698351

it says `Only one .nimble file should be present in /home/runner/work/nimibook/nimibook`.

Is there some caching mechanism happening there and it still has `nimiBook.nimble`?

I will try to run it again

**Comment by pietroppeter** [comment]
did not work. should I try to rename the nimble file also in gh-pages branch? sounds a dirty thing to do...

**Comment by HugoGranstrom** [comment]
Sounds really odd, have never seen it before 🤔 And yes it's odd that it is the old one in the gh-pages branch. Is only part of the repo force pushed to the other branch?

**Comment by pietroppeter** [comment]
well, in gh-pages it is the old one since it never arrived to the stage of committing the change rebased from main.

**Comment by HugoGranstrom** [comment]
Okay, missed that detail 👍 it says nimiBook with big B in the nimble install so it is still left for sure. Maybe run `rm nimiBook.nimble` before installing?

**Comment by pietroppeter** [comment]
yeah as a patch solution maybe adding (and later removing) `rm -f nimiBook.nimble` from CI is a better fix than messing with gh-pages branch

**Comment by pietroppeter** [comment]
it worked (path to CI added and removed)!

**Comment by HugoGranstrom** [comment]
Oh nice! 😁
