### ISSUE TITLE
highlight nim code in pages with markdown sources

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nimibook#64]
- need to recover a nim highlight js file (see this PR which removed it from nimib some time ago https://github.com/pietroppeter/nimib/pull/15/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
- add it to assets
- add it as a script in head: https://github.com/pietroppeter/nimib/issues/68
- initialize the script in body

see also https://github.com/pietroppeter/nimib/issues/68 (where there is the discussion for other languages than nim, which also should be in scope here)
the feature should likely be implemented first in nimib and then used here.

**Comment by pietroppeter** [comment]
closed by #74

**Comment by pietroppeter** [comment]
bizarrely enough this commands section is highlighted as sql: https://pietroppeter.github.io/nimibook/cli.html probably can be overridden by mentioning something (bash?) after the backticks. not planning to do anything about it for now.

**Comment by HugoGranstrom** [comment]
I think you can mark the language as `plaintext` If you don't want any highlighting of a code block.

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________
