### ISSUE TITLE
Licensing of embedded assets

### ISSUE THREAD

**Issue by can-lehmann** [pietroppeter/nimibook#80]
I am currently working on fulfilling the legal prerequisites for merging https://github.com/can-lehmann/owlkettle/pull/34. As discussed before on Discord, I would like to compile a list of licenses for the assets redistributed as part of the resulting website. So far I primarily looked at the files in the `assets` folder. The following is the section I plan to include in owlkettles docs.

> We use [nimibook](https://github.com/pietroppeter/nimibook) to build this documentation. Nimibook is licensed under the MIT license.
>
> When building a website using nimibook, various assets (code, fonts, styles) are redistributed as part of the website. Here are the licenses for the assets distributed as part of this website. Click on one of the assets to view its license. Note that these licenses only apply to the indicated assets redistributed as part of this website, **not** to owlkettle or its documentation text.
>
> - Fonts
>   - [Open Sans](https://github.com/pietroppeter/nimibook/blob/main/src/nimibook/assets/fonts/OPEN-SANS-LICENSE.txt) (Apache License 2.0)
>   - [Source Code Pro](https://github.com/pietroppeter/nimibook/blob/main/src/nimibook/assets/fonts/SOURCE-CODE-PRO-LICENSE.txt) (SIL Open Font License, Version 1.1)
>   - FontAwesome
>     - [Fonts](http://scripts.sil.org/OFL) (SIL OFL 1.1)
>     - [CSS](http://opensource.org/licenses/mit-license.html) (MIT)
> - Code
>   - [clipboard.js](https://github.com/zenorocha/clipboard.js/blob/master/LICENSE) (MIT)
>   - [Highlight.js](https://github.com/highlightjs/highlight.js/blob/main/LICENSE) (BSD-3-Clause)
>   - [book.js](https://github.com/rust-lang/mdBook/blob/master/LICENSE) (MPL-2.0)
> - [Themes](https://github.com/rust-lang/mdBook/blob/master/LICENSE) (MPL-2.0)

It would be great if you could double check that I didn't miss anything.

I also have a specific question regarding the licensing of [book.js](https://github.com/pietroppeter/nimibook/blob/main/src/nimibook/assets/js/book.js). I assumed that is licensed under MPL-2.0, since it seems to come from mdBook, which itself is MPL-2.0. Is that correct?

The assumption is based on Section 3.1 of the MPL which states that:

> All distribution of Covered Software in Source Code Form, including any Modifications that You create or to which You contribute, must be under the terms of this License.

Note that I am not a lawyer, my understanding of software licenses is quite limited, so take all of this with a grain of salt :smiley:

**Comment by pietroppeter** [comment]
That list seems correct from a quick review but I will double check when I have a bit more time. I agree that book.js should also be MPL 2.0.

thanks for working on this, after double checking I think it could be worth to put this kind of detail in the readme (and keep it maintained).

**Comment by can-lehmann** [comment]
Thank you! I think it would be great to have this kind of legal documentation available for users of nimibook. As far as I know nimibook optionally uses KaTeX for math typesetting, so you would also need to add that to the list (idk if there are any terms for plausible analytics).

I think that ideally this information would be automatically included in the document and accessible through a small link somewhere on the page. This way the licensing information stays up to date no matter which nimibook version is used.

**Comment by pietroppeter** [comment]
I had a bit of time to double check and it seems all correct. The only detail I could find is the fact that the some of the css of themes are based on versions which are themselves MIT licensed, not sure if inclusion of mdbook makes them change the license or not, it is likely they have been modified so I guess it is fair to list them with the license of mdbook. The specific themes are:
- https://github.com/dempfi/ayu
- https://github.com/chriskempson/tomorrow-theme

**Comment by can-lehmann** [comment]
Thank you for double checking the list. I added the two themes you listed to the licensing page: https://can-lehmann.github.io/owlkettle/book/legal/license.html I am not sure if nimibook's use here constitutes a "substantial portion" under the MIT license, but I guess including them does not hurt either :)

**Comment by PhilippMDoerner** [comment]
What would this ticket require to be closed out of curiosity?
A PR with a new page "Licenses" for the [nimibook of nimibook](https://pietroppeter.github.io/nimibook/) that explains what parts are under what License?

**Comment by pietroppeter** [comment]
Yep, a new page for nimibook would be good. Probably we could add also a `nimibook/license` module that contains a single constant with the text that we want to show so that other libraries can reuse the same text (and it gets updated automatically).

**Comment by PhilippMDoerner** [comment]
I've made a PR for the additional page.
As I keep being neck deep in owlkettle and am very bad at mutlitasking different topics, I hesitate to make that dive into nimibook.
Rather "superficial" work such as just adding a page seemed like a no brainer though, so I just did it.

Do you think it would make sense to split out making a "license"-module into its own issue?

**Comment by pietroppeter** [comment]
Thanks, I will try to merge and close also the license module thing during the day. Thanks for getting the ball rolling!

**Comment by pietroppeter** [comment]
closed by #80.

opened related #87 for license module
