### ISSUE TITLE
Possible issue in parallel builds when two file have the same name

### ISSUE THREAD

**Issue by HugoGranstrom** [pietroppeter/nimibook#81]
I have multiple files named `index.nim` in my nimiBook in nimiSlides. And I have gotten two errors in the C-compiler/linker regarding this: [link to job](https://github.com/HugoGranstrom/nimiSlides/actions/runs/5255951959/jobs/9496553035?pr=23) And I suspect that it might be due to them using the same filenames in nimcache. This is problematic as you typically have multiple `index.nim` files in a book (one for each section). 

A possible solution to this would be to only allow a single file of each filename to be built at the same time. So if a `index.nim` file is already being built, and another `index.nim` file is about to be built as well, it will be put aside until the other file has finished. 

I think this could be done using a global `HashSet[string]` and adding a condition [here](https://github.com/pietroppeter/nimibook/blob/1405553199b12915a502df8b871ffe86dcfc5e91/src/nimibook/builds.nim#L16) that checks if the current filename is already in the set or not.

**Comment by pietroppeter** [comment]
Isn't there some compiler option that allows to override the name of file in cache? If so we could just add the index of the file in the list of file to build or something else to disambiguate

**Comment by HugoGranstrom** [comment]
I would say it depends on what `-o:outputname` does when using `nim r` as there is no non-temporary binary to save. Hopefully it uses that name as well in the cache but I'm not holding my hopes up 😬 will investigate it further tomorrow, I hope I'm wrong though.

**Comment by pietroppeter** [comment]
another option would be to override the Nim cache folder and replicate the folder structure of source files (+ a base folder that could be the default one)

**Comment by pietroppeter** [comment]
well if I understand correctly we have issues with a structure like this:
```
index.nim
section1/index.nim
```
because when processed concurrently nim creates c files with the same name in nimcache folder (calling it `$nimcache` here), like `$nimcache/index.c`. If instead we ask for the second index file to use as nimcache `$nimcache/section1` (so that the c file is `$nimcache/index.c`/index.c` this should solve the issue, right?

**Comment by pietroppeter** [comment]
still, I had a brief look at the log and not entirely sure the issue is conflict of filenames:
I see a name like `/home/runner/.cache/nim/index_d/index_48315C86F820572F8ADD5336011EE02A9F1B2C7F` and it looks like filenames are mangled? maybe it is an issue when filenames have same name and same content?

and to be honest I have only a limited knowledge of nimcache logic...

**Comment by HugoGranstrom** [comment]
Yes that sounds like it could work. And we would get the benefit of all the cache being intact 👍

**Comment by pietroppeter** [comment]
ah but you have also stuff like `/home/runner/.cache/nim/index_d/@mindex.nim.c.o` so that might create a conflict anyway

**Comment by HugoGranstrom** [comment]
> ah but you have also stuff like `/home/runner/.cache/nim/index_d/@mindex.nim.c.o` so that might create a conflict anyway

Yes exactly, it's those that are the problem I think because it was the C compiler that complained about not finding references. Which would be because we have overridden some file before it was finished compiling or something like that

**Comment by HugoGranstrom** [comment]
I will try to fix this in the coming week. What I've found is that it's as easy as passing `--nimcache:path` to change the nimcache folder. And we can get the current nimcache folder using this code from [forum thread](https://forum.nim-lang.org/t/3548):
```nim
import std/compilesettings
const nimcache = querySetting(SingleValueSetting.nimcacheDir)
```

So we just have to combine this `nimcache` with the relative path of the current document to get the desired results.
